const reader = document.querySelector("#story-panel");
const backToTop = document.querySelector(".back-to-top");
const tabs = [...document.querySelectorAll("[data-story]")];
const tolstoySections = [[0,"the-shoemaker","The Shoemaker"],[22,"the-gospel","The Gospel"],[42,"christmas-morning","Christmas Morning"],[52,"stepanuitch","Stepanuitch"],[75,"the-mother-and-child","The Mother and Child"],[106,"the-apple-woman","The Apple Woman"],[139,"the-visitor","The Visitor"]];
let stories, selected = "tolstoy", openNote = null, sectionData = [];
const slug = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");

function makeFootnote(id, label, notes) {
  const wrap = document.createElement("span"); wrap.className = "footnote-wrap";
  const button = document.createElement("button"); button.type = "button"; button.className = "footnote-marker"; button.setAttribute("aria-label", `Footnote ${label}`); button.setAttribute("aria-expanded", "false"); button.innerHTML = `<sup>${label}</sup>`;
  const popover = document.createElement("span"); popover.className = "footnote-popover"; popover.setAttribute("role", "note"); popover.textContent = notes[id];
  button.addEventListener("click", (event) => { event.stopPropagation(); const next = openNote === wrap ? null : wrap; document.querySelectorAll(".footnote-wrap.is-open").forEach((item) => { item.classList.remove("is-open"); item.querySelector("button").setAttribute("aria-expanded","false"); }); openNote = next; if (next) { wrap.classList.add("is-open"); button.setAttribute("aria-expanded","true"); } });
  wrap.append(button, popover); return wrap;
}
function addParagraph(parent, text, index, notes) {
  const p = document.createElement("p");
  text.split(/(\(\d+\))/g).forEach((part) => { const match = part.match(/^\((\d+)\)$/); p.append(match && notes[match[1]] ? makeFootnote(match[1],match[1],notes) : document.createTextNode(part)); });
  if (selected === "saillens" && index === 153 && notes.saillens) p.append(makeFootnote("saillens","*",notes));
  parent.appendChild(p);
}
function renderStory(key) {
  selected = key; const story = stories[key]; tabs.forEach((tab) => tab.setAttribute("aria-selected", String(tab.dataset.story === key)));
  const notes = {}; story.blocks.forEach((block) => { const match = block.text.match(/^\((\d+)\)\s*(.*)$/s); if (match) notes[match[1]] = match[2]; }); const special = story.blocks.find((block) => block.text.startsWith("Translator's note:")); if (special) notes.saillens = special.text.replace(/^Translator's note:\s*/,"");
  sectionData = key === "tolstoy" ? tolstoySections.map(([index,id,label]) => ({index,id,label})) : story.blocks.map((block,index) => ({block,index})).filter(({block}) => block.type === "heading").map(({block,index}) => ({index,id:slug(block.text),label:block.text}));
  reader.innerHTML = `<div class="reading-layout"><aside class="reading-progress" aria-label="Reading progress"><div class="progress-heading"><span>0%</span><div class="progress-rule"><i></i></div></div><nav aria-label="Story sections"></nav><label class="mobile-section"><span>Jump to section</span><select></select></label></aside><article class="story-reader-inner"><header class="story-header"><p class="eyebrow">${story.author}</p><h2>${story.title}</h2><p>${story.credit}</p></header></article></div>`;
  const article = reader.querySelector(".story-reader-inner");
  if (key === "saillens") { const note = document.createElement("details"); note.className="translator-note"; note.innerHTML='<summary>Translator’s note <span aria-hidden="true">+</span></summary><div class="translator-note-body"><a href="#story-start" class="skip-note">Skip to story ↓</a></div>'; const body=note.querySelector("div"); story.translatorNote.forEach((b)=>{const el=document.createElement(b.type==="heading"?"h3":"p");el.textContent=b.text;body.append(el)}); article.append(note); }
  else { const source=document.createElement("p");source.className="story-source";source.innerHTML=`<a href="${story.sourceUrl}" target="_blank" rel="noopener noreferrer">${story.sourceLabel} ↗</a>`;article.append(source); }
  const text=document.createElement("div");text.className="story-text";text.id="story-start";
  story.blocks.forEach((block,index)=>{ if (/^\(\d+\)/.test(block.text)||block.text.startsWith("Translator's note:")) return; const section=sectionData.find((item)=>item.index===index); if(key==="tolstoy"&&section){const container=document.createElement("section");container.id=section.id;container.dataset.section=section.id;container.className="story-section";const h=document.createElement("h3");h.textContent=section.label;container.append(h);addParagraph(container,block.text,index,notes);text.append(container)}else if(block.type==="heading"){const h=document.createElement("h3");h.textContent=block.text;if(section){h.id=section.id;h.dataset.section=section.id}text.append(h)}else addParagraph(text,block.text,index,notes)}); article.append(text);
  const nav=reader.querySelector(".reading-progress nav"), select=reader.querySelector(".mobile-section select"); sectionData.forEach((section)=>{const button=document.createElement("button");button.type="button";button.textContent=section.label;button.addEventListener("click",()=>document.getElementById(section.id).scrollIntoView({behavior:"smooth",block:"start"}));nav.append(button);const option=document.createElement("option");option.value=section.id;option.textContent=section.label;select.append(option)});select.addEventListener("change",()=>document.getElementById(select.value).scrollIntoView({behavior:"smooth",block:"start"}));
  history.replaceState(null,"",`/read?story=${key}`); updateProgress();
}
function updateProgress(){backToTop.classList.toggle("visible",scrollY>80);const article=reader.querySelector(".story-reader-inner");if(!article)return;const rect=article.getBoundingClientRect(),distance=Math.max(1,rect.height-innerHeight*.55),value=Math.max(0,Math.min(100,((innerHeight*.28-rect.top)/distance)*100)),percent=Math.round(value);reader.querySelector(".progress-heading span").textContent=`${percent}%`;reader.querySelector(".progress-rule i").style.width=`${value}%`;let active=sectionData[0]?.id;reader.querySelectorAll("[data-section]").forEach((marker)=>{if(marker.getBoundingClientRect().top<=innerHeight*.34)active=marker.dataset.section});reader.querySelectorAll(".reading-progress nav button").forEach((button,index)=>button.classList.toggle("active",sectionData[index]?.id===active));const select=reader.querySelector(".mobile-section select");if(active)select.value=active;[...select.options].forEach((option)=>option.textContent=`${sectionData.find((s)=>s.id===option.value).label} · ${percent}%`)}
backToTop.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));
document.addEventListener("click",(event)=>{if(!event.target.closest(".footnote-wrap")){document.querySelectorAll(".footnote-wrap.is-open").forEach((item)=>item.classList.remove("is-open"));openNote=null}});document.addEventListener("keydown",(event)=>{if(event.key==="Escape"){document.querySelectorAll(".footnote-wrap.is-open").forEach((item)=>item.classList.remove("is-open"));openNote=null}});addEventListener("scroll",updateProgress,{passive:true});addEventListener("resize",updateProgress);
fetch("/stories.json").then((response)=>response.json()).then((data)=>{stories=data;const requested=new URLSearchParams(location.search).get("story");renderStory(requested==="saillens"?"saillens":"tolstoy");tabs.forEach((tab,index)=>{tab.addEventListener("click",()=>renderStory(tab.dataset.story));tab.addEventListener("keydown",(event)=>{if(!["ArrowLeft","ArrowRight"].includes(event.key))return;event.preventDefault();const next=event.key==="ArrowRight"?(index+1)%tabs.length:(index-1+tabs.length)%tabs.length;tabs[next].focus();tabs[next].click()})})}).catch(()=>{reader.innerHTML='<p class="story-loading">The story could not be opened. Please refresh the page.</p>'});
